class CustomError(Exception):
    pass

raise CustomError("An error occurred")